spring.datasource.url=jdbc:postgresql://localhost:5432/smartscheduller
spring.datasource.username=smartscheduller
spring.datasource.password=smartscheduller
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2

spring.jpa.show-sql=true

logging.level.com.smartscheduller=DEBUG
logging.level.org.hibernate.SQL=DEBUG

